### ISSUE TITLE
Still maintained?

### ISSUE THREAD

**Issue by dandv** [Travelport-Ukraine/npm-module-boilerplate#92]
greenkeeper PRs haven't been merged this year.

Also, there are more modern and more actively maintained projects:

* https://github.com/jsynowiec/node-flowtype-boilerplate
* https://github.com/diegohaz/nod

**Comment by shmuga** [comment]
Will make some updates shortly!
Not sure if Flow is needed in this boilerplate.

**Comment by codecomp** [comment]
Is this still planned to be updated? After spending 5 hours today looking through different ES6 supported module boilerplates this seems to be one of the better ones without much of the unexplained bloat of others. But it is in need of an update as installing triggers numerous depreciated errors and warnings. Even the linting task out of the box triggers a critical error on the npm-module-boilerplate-es6@1.0.0 lint script

**Comment by shmuga** [comment]
@Codecomp @dandv I have recently updated package to latest version of dependencies. Also I've removed plugin for default export mutation for ES6 modules and added babel-preset-env to configure needed target of babel transformation. 

For now I'm not planning to add type system to this boilerplate. If there is such need we can join our forces and make some kind of TS/Flow boilerplates.

**Comment by shmuga** [comment]
Feel free to close the issue if there are no more questions.
